### ISSUE TITLE
the licence agreement

### ISSUE THREAD

**Issue by suzune9999** [pirelenito/react-transition#5]
I'd like to know what is the licence agreement for "react-transition".
The MIT License ?

Thank you.

**Comment by pirelenito** [comment]
Yes it is! I should add it to the repository. Sorry.

However I would recommend you use something like [react-motion](https://github.com/chenglou/react-motion) instead, since that project got a lot more traction and is being actively developed.

Thanks for passing by!

**Comment by suzune9999** [comment]
Thank you for your answer and recommendation.
I would consider using react-motion. Anyway thanks a lot.
